
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'ADMIN',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS party_accounts(id TEXT PRIMARY KEY,ledger_no TEXT UNIQUE,party_name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS party_payments(id TEXT PRIMARY KEY,party_name TEXT NOT NULL,payment_date TEXT NOT NULL,amount REAL NOT NULL CHECK(amount>=0),payment_mode TEXT,reference TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trucks(id TEXT PRIMARY KEY,truck_no TEXT UNIQUE NOT NULL,owner_name TEXT,bank_details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS routes(id TEXT PRIMARY KEY,loading_point TEXT NOT NULL,unloading_point TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(loading_point,unloading_point));
CREATE TABLE IF NOT EXISTS materials(id TEXT PRIMARY KEY,material_name TEXT UNIQUE NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trips(id TEXT PRIMARY KEY,trip_date TEXT,party_name TEXT,truck_no TEXT,loading_point TEXT,unloading_point TEXT,material TEXT,weight REAL DEFAULT 0 CHECK(weight>=0),rate REAL DEFAULT 0 CHECK(rate>=0),status TEXT DEFAULT 'BOOKED',pod_file_name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS invoices(id TEXT PRIMARY KEY,invoice_no TEXT UNIQUE NOT NULL,invoice_date TEXT,party_name TEXT,trip_id TEXT,lr_no TEXT,material TEXT,truck_no TEXT,weight REAL DEFAULT 0,rate REAL DEFAULT 0,diesel REAL DEFAULT 0,munshi REAL DEFAULT 0,subtotal REAL DEFAULT 0,gst_percent REAL DEFAULT 0,gst_amount REAL DEFAULT 0,total REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS truck_payments(id TEXT PRIMARY KEY,entry_date TEXT,truck_no TEXT,owner_name TEXT,loading_point TEXT,unloading_point TEXT,weight REAL DEFAULT 0,rate REAL DEFAULT 0,commission REAL DEFAULT 0,payable REAL DEFAULT 0,paid_amount REAL DEFAULT 0,pending REAL DEFAULT 0,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expenses(id TEXT PRIMARY KEY,expense_date TEXT,category TEXT,amount REAL DEFAULT 0 CHECK(amount>=0),notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS truck_documents(id TEXT PRIMARY KEY,truck_no TEXT NOT NULL,kind TEXT NOT NULL,file_name TEXT,file_url TEXT,expiry_date TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,user_id INTEGER,action TEXT,entity TEXT,entity_id TEXT,payload TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_trips_party ON trips(party_name);
CREATE INDEX IF NOT EXISTS idx_trips_truck ON trips(truck_no);
CREATE INDEX IF NOT EXISTS idx_trips_date ON trips(trip_date);
CREATE INDEX IF NOT EXISTS idx_invoices_party ON invoices(party_name);
CREATE INDEX IF NOT EXISTS idx_invoices_trip ON invoices(trip_id);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(invoice_date);
CREATE INDEX IF NOT EXISTS idx_party_payments_party ON party_payments(party_name);
CREATE INDEX IF NOT EXISTS idx_party_payments_date ON party_payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_truck_payments_owner ON truck_payments(owner_name);
CREATE INDEX IF NOT EXISTS idx_truck_payments_truck ON truck_payments(truck_no);
CREATE INDEX IF NOT EXISTS idx_truck_payments_date ON truck_payments(entry_date);
CREATE INDEX IF NOT EXISTS idx_documents_truck ON truck_documents(truck_no);
